export const POST_LIKE = 'POST_LIKE';
export const POST_LIKE_COMMENT = 'POST_LIKE_COMMENT';
export const POST_ADD_COMMENT = 'POST_ADD_COMMENT'; 

// post uploading
export const POST_UPLOAD_START = 'POST_UPLOAD_START';

export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';

// AUTH
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';